# Code of Conduct {#code}

A _Code of Conduct_ is a set of basic ground rules that we ask all of AFSC-Genetics to follow. The goal is to create an open and inclusive space for our work that helps us achieve our collective goals. By virtue of being part of the AFSC community, we each benefit from our strong scientific and inter-personal culture. Likewise, we each share the responsibility to champion the workplace attributes we enjoy and value most. 

__We expect all AFSC-Genetics members to adhere to the policies and guidelines outlined here.__  

[AFSC Code of Conduct](https://drive.google.com/file/d/1wAq-nuvPLuP3hp2ktSp0d8YdMYo8coOh/view?usp=sharing).  


## Short version

AFSC-Genetics is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, age, race, or religion. We do not tolerate harassment of participants in any form and prioritize marginalized people’s safety over privileged people’s comfort.  

This code of conduct applies to all AFSC-Genetics activities, including group and individual meetings (face to face and remote), workshops, labwork, fieldwork, social events, and email correspondence.

## Longer version - still need to edit

AFSC-Genetics is dedicated to providing a harassment-free experience for everyone. We do not tolerate harassment of group members or others in our larger communities in any form. Bullying is unwanted, aggressive behavior that involves a real or perceived power imbalance. 

This code of conduct applies to all Genetics lab spaces, including group and individual meetings (face to face and remote), workshops, social get togethers, email correspondence, and web channels and code repositories, both online and off. Anyone who violates this code of conduct may be sanctioned and referred to AFSC policies.  
 
Harassment includes:  

* Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, age, race, or religion.  
* Unwelcome comments regarding a person’s lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment.
* Deliberate misgendering or use of ‘dead’ or rejected names.
* Gratuitous or off-topic sexual images or behaviour in spaces where they’re not appropriate.
* Physical contact and simulated physical contact (eg, textual descriptions like “*hug*” or “*backrub*”) without consent or after a request to stop.
* Threats of violence.
* Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
* Deliberate intimidation.
* Stalking or following.
* Harassing photography or recording, including logging online activity for harassment purposes.
* Sustained disruption of discussion.
* Unwelcome sexual attention.
* Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others
* Continued one-on-one communication after requests to cease.
* Deliberate “outing” of any aspect of a person’s identity without their consent except as necessary to protect vulnerable people from intentional abuse.
* Publication of non-harassing private communication.  

### Reporting - still need to edit

If you are being harassed by a member of the Genetics lab, notice that someone else is being harassed, or have any other concerns, please contact the PI, INSERT NAME, at [XXX@noaa.gov](mailto:XXX@noaa.gov). Lab members who believe they have been subjected to any kind of discrimination that conflicts with AFSC policies should seek assistance from a supervisor or an HR representative. 

This code of conduct applies to Genetics lab spaces, but if you are being harassed by a member of the Genetics lab outside our spaces, we still want to know about it. We will take all good-faith reports of harassment seriously. This includes harassment outside our spaces and harassment that took place at any point in time. To protect our team members from abuse and burnout, we reserve the right to reject any report we believe to have been made in bad faith. Reports intended to silence legitimate criticism may be deleted without response.  

The above caveats noted, we will respect confidentiality requests for the purpose of protecting victims of abuse when possible. At our discretion, we may publicly name a person about whom we’ve received harassment complaints, or privately warn third parties about them, if we believe that doing so will increase the safety of the Genetics lab members. We will not name harassment victims without their affirmative consent.  

### Consequences - still need to edit

Participants asked to stop any harassing behavior are expected to comply immediately.  

If a participant engages in harassing behavior, appropriate action will be taken, which includes referral to HR per AFSC policy, and expulsion from all Genetics lab spaces.  

### Additional resources - still need to edi


## License and attribution - still need to edit

This code of coduct and anti-harassment policy is based on the [example policy created by the Geek Feminism community](https://geekfeminism.wikia.org/wiki/Community_anti-harassment) and University of Massachusetts Fay Lab code of conduct. It has been reviewed by the current AFSC-Genetics lab supervisor and members. 
