project: 
  type: book
  
book:

  chapters: [
  "index.qmd",
  "01-intro-how-we-work.qmd",
  "02-lab-culture-philosophy.qmd",
  "03-code-of-conduct.qmd",
  "04-onboarding.qmd",
  "05-expectations.qmd",
  "06-offboarding.qmd",
  "07-funding.qmd",
  "08-communication.qmd",
  "09-academics.qmd",
  "10-courses.qmd",
  "11-computing.qmd",
  "12-umassd-resources.qmd",
#  "13-smast-resources.qmd",
#  "14-other-faylab-resources.qmd",  
]
