project: 
  type: book
  output-dir: _book
  
book:
  title: "MML Manual"
  author: "Nancy Friday, Katie Luxa, Cynthia Christman, Erin Moreland, and Kim Shelden"
  date: last-modified 
#  description: "This is the lab manual for the Marine Mammal Laboratory at the Alaska Fisheries Science Center" 
  
  page-footer:
    left: |
      <a href="https://www.fisheries.noaa.gov/about/marine-mammal-laboratory">Marine Mammal Laboratory</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://thefaylab.github.io/lab-manual/
  repo-url: https://github.com/thefaylab/lab-manual
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-code-of-conduct.qmd
    - 02-onboarding.qmd
    - 03-offboarding.qmd
    - 04-outreach.qmd
    - 05-safety.qmd
    - 06-other-resources.qmd
#    - 14-aviation.qmd


# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

