project: 
  type: book
  
book:
  title: "Faylab Lab Manual"
  author: "Gavin Fay & Ashleigh Novak"
  date: last-modified 
  description: "This is the lab manual for the Fay Lab at the University of Massachusetts Dartmouth School for Marine Science and Technology" 
  repo-url: https://github.com/thefaylab/lab-manual
  repo-actions: [edit,issue]
  chapters: [
  "index.qmd",
  "01-intro-how-we-work.qmd",
  "02-lab-culture-philosophy.qmd",
  "03-code-of-conduct.qmd",
  "04-onboarding.qmd",
  "05-expectations.qmd",
  "06-offboarding.qmd",
  "07-funding.qmd",
  "08-communication.qmd",
  "09-academics.qmd",
  "10-courses.qmd",
  "11-computing.qmd",
  "12-umassd-resources.qmd",
#  "13-smast-resources.qmd",
#  "14-other-faylab-resources.qmd",  
]

bibliography: [references.bib, book.bib]

